name: Prepared project to Compilation Android

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Prepared_code:
    
    runs-on: ubuntu-latest

    steps:

      - name: Get Code from repository
        uses: actions/checkout@v4

      - name: Check files in main Folder
        run: ls -hl

      - name: Remove android about module old folder link
        run: |
              rm -rf japl-android-about-module
              rm -rf ScheduleModule
              rm -rf connect-gdrive
              rm -rf japl-android-graphs

      - name: Get japl-android-about-module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-about-module
          path: ./japl-android-about-module

      - name: Get japl-android-schedule-module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-schedule-module
          path: ./ScheduleModule

      - name: Get japl-android-google-connect-module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-google-connect-module
          path: ./connect-gdrive

      - name: Get Finances to get Graphs module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/Finances
          path: ./finances

      - name: link code to graphs folder
        run: ln -s ./finances/japl-android-graphs ./japl-android-graphs 

      - name: Install Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17

      - name: Setup Graddle And Validations
        uses: gradle/actions/setup-gradle@v4

      - name: build and scan
        run: ./gradlew build --scan --warning-mode all

      - name: Upload builds reports 
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: '**/build/reports/'

      
      - name: Check files in main Folder
        if: always()
        run: ls -hl
