name: Prepared project to Compilation Android

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Prepared_code:
    environment: PROD
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare
        with: 
          SECRET_TOKEN: ${{ secrets.GH_PROPERTIES_CONNECT }}
      
      - name: added signing in gradle
        run: |
            cat << EOF >> app/build.gradle
              android {
                signingConfigs {
                  create("release") {
                    storeFile = file("./torressansebastian.jks")
                    storePassword = "${{ secrets.SIGNING_STORE_PASSWORD }}"
                    keyAlias = "${{ secrets.SIGNING_KEY_ALIAS }}"
                    keyPassword = "${{ secrets.SIGNING_KEY_PASSWORD }}"
                  }
                }

              buildTypes {
                getByName("release") {
                  signingConfig = signingConfigs.getByName("release")
                }
              }
            }
            EOF

      - name: build and scan
        run: ./gradlew bundleRelease --no-daemon --no-parallel --info # build --scan --warning-mode all --stacktrace --info
      
      - name: Upload builds reports 
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: |
                **/build/reports/
                ./app/build/outputs/bundle/release/
                /home/runner/_temp/.gradle-actions/build-results/

  test-task:
   uses: ./.github/workflows/test-lint.yaml

