name: Prepared project to Compilation Android

on:
  workflow_dispatch:

jobs:

  Prepared_code:
    
    runs-on: ubuntu-latest

    steps:

      - name: Get Code from repository
        uses: actions/checkout@v4

      - name: Check files in main Folder
        run: ls 

      - name: Get japl-android-about-module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-about-module
          path: japl-android-about-module

      - name: Check files in main Folder
        run: ls 
