name: Execute Test with Lint gradle

on: 
  workflow_dispatch:

jobs:

  config_repository:
   runs-on: ubuntu-latest
   environment: PROD

   steps:

    - uses: actions/checkout@v4
    
    - name: Get project settings
      uses: ./.github/actions/prepare
      with:
        SECRET_TOKEN: ${{ secrets.GH_PROPERTIES_CONNECT }}
      
